{{- if .Values.redis.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.redis.serviceAccount.name }}
  labels:
{{ include "redis.labels" . | nindent 4 }}
{{- end -}}